baseurl                 = "https://ozcanoguz.com.tr"
languageCode            = "tr-tr"
defaultContentLanguage  = "tr"
isMultilingual          = true
title                   = "Özcan Oğuz"
theme                   = "sam"
pygmentsStyle           = "monokai"
pygmentsCodefences      = true

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "favicon.ico"
    homepage            = "main"
    galleryFolder       = "images/"
    clickablePhotos     = true
    smallPreviewImages   = true
    smallImagesSubfolder = "small/"                      # The subfolder for the small versions of the images under the gallery (with trailing slash)
                                                         # For each image the small version has to have the same filename as the big version.
    footerText          = "©2018-2020 Özcan Oğuz. CC BY-SA 4.0"

# Metadata
    description         = "Özcan Oğuz'un kişisel web sitesi"            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "tn.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/about"
    text = "hakkımda"

[[params.mainMenu]]
    link = "/portfolio"
    text = "portfolyo"

[[params.mainMenu]]
    link = "/posts"
    text = "yazılar"

[[params.mainMenu]]
    link = "/gallery"
    text = "galeri"
